/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kf5012assessment;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author w21023500
 */
public class CreateNewChoreGUI extends javax.swing.JDialog {

    ArrayList<Chore> choress;

    /**
     * Creates new form CreateNewChoreGUI
     */
    private SelectWeeklyChoreGUI mainWindow;

    /**
     * Creates new form NewTaskChore
     *
     * @param parent
     */
    public CreateNewChoreGUI(SelectWeeklyChoreGUI parent, boolean modal) {
        super(parent, modal);
        this.mainWindow = parent;
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(oneOffChoreType);
        bg.add(weeklyChoreType);
        weeklyChoreType.setSelected(true);

    }

    public CreateNewChoreGUI() {
        initComponents(); // initialize the components of your GUI
        setVisible(true); // make the GUI visible

    }

    public SelectWeeklyChoreGUI getMainWindow() {
        return mainWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weeklyChoreType = new javax.swing.JRadioButton();
        oneOffChoreType = new javax.swing.JRadioButton();
        newChoreTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        newDaysTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        submitNewChoreButton = new javax.swing.JButton();
        cancelNewChoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Chore Name:");

        jLabel2.setText("Chore Type:");

        buttonGroup.add(weeklyChoreType);
        weeklyChoreType.setText("Weekly");
        weeklyChoreType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyChoreTypeActionPerformed(evt);
            }
        });

        buttonGroup.add(oneOffChoreType);
        oneOffChoreType.setText("One-off ");
        oneOffChoreType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneOffChoreTypeActionPerformed(evt);
            }
        });

        newChoreTextField.setText("Chore");
        newChoreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newChoreTextFieldActionPerformed(evt);
            }
        });

        newDaysTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newDaysTable);
        if (newDaysTable.getColumnModel().getColumnCount() > 0) {
            newDaysTable.getColumnModel().getColumn(0).setResizable(false);
            newDaysTable.getColumnModel().getColumn(1).setResizable(false);
            newDaysTable.getColumnModel().getColumn(2).setResizable(false);
            newDaysTable.getColumnModel().getColumn(3).setResizable(false);
            newDaysTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Select the fequency of the chore");

        submitNewChoreButton.setText("Submit");
        submitNewChoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewChoreButtonActionPerformed(evt);
            }
        });

        cancelNewChoreButton.setText("Cancel");
        cancelNewChoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewChoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(newChoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(weeklyChoreType)
                                .addGap(26, 26, 26)
                                .addComponent(oneOffChoreType))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelNewChoreButton)
                .addGap(29, 29, 29)
                .addComponent(submitNewChoreButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newChoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(weeklyChoreType)
                    .addComponent(oneOffChoreType))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitNewChoreButton)
                    .addComponent(cancelNewChoreButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void oneOffChoreTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneOffChoreTypeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_oneOffChoreTypeActionPerformed

    private void weeklyChoreTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyChoreTypeActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_weeklyChoreTypeActionPerformed

    private void newChoreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newChoreTextFieldActionPerformed


    }//GEN-LAST:event_newChoreTextFieldActionPerformed

    private void submitNewChoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewChoreButtonActionPerformed

        if (newChoreTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "pls fill in a chore!");

        } else {
            String textNewChore = newChoreTextField.getText().trim();

        }
        if (oneOffChoreType.isSelected()) {
            ChoresDatabase choresDB = new ChoresDatabase();
            try {
                ArrayList<Chore> oneOffChores = choresDB.selectChoresFrequencyOneOff();
                // Perform operations with oneOffChores ArrayList
            } catch (SQLException ex) {
                Logger.getLogger(CreateNewChoreGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (weeklyChoreType.isSelected()) {
            ChoresDatabase choresDB = new ChoresDatabase();
            try {
                ArrayList<Chore> weeklyChores = choresDB.selectChoresFrequencyWeekly();
                // Perform operations with weeklyChores ArrayList
            } catch (SQLException ex) {
                Logger.getLogger(CreateNewChoreGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        Chore chore = new Chore();

        // Close the dialog
        this.dispose();


    }//GEN-LAST:event_submitNewChoreButtonActionPerformed

    private void cancelNewChoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewChoreButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel creating a new task?", "Confirm Cancel", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); //gets rid of the screen  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cancelNewChoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewChoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewChoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewChoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewChoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreateNewChoreGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelNewChoreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newChoreTextField;
    private javax.swing.JTable newDaysTable;
    private javax.swing.JRadioButton oneOffChoreType;
    private javax.swing.JButton submitNewChoreButton;
    private javax.swing.JRadioButton weeklyChoreType;
    // End of variables declaration//GEN-END:variables
}
