/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.kf5012assessment;

import javax.swing.JOptionPane;

/**
 *
 * @author w21010679
 */
public class NewTaskChore extends javax.swing.JDialog {

    private GUIOfCommonChores mainWindow;

    /**
     * Creates new form NewTaskChore
     *
     * @param parent
     */
    public NewTaskChore(GUIOfCommonChores parent, boolean modal) {
        super(parent, modal);
        this.mainWindow = parent;
        initComponents();
    }

    public GUIOfCommonChores getMainWindow() {
        return mainWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTaskName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        newTaskTextArea = new javax.swing.JTextArea();
        estimatedTimeTextArea = new javax.swing.JTextField();
        newEstimatedTimeSlider = new javax.swing.JSlider();
        okNewTask = new javax.swing.JButton();
        cancelNewTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        newTaskName.setText("Task Name ");
        newTaskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTaskNameActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please fill out this form to add \nyour one off task ");
        jScrollPane1.setViewportView(jTextArea1);

        newTaskTextArea.setColumns(20);
        newTaskTextArea.setRows(5);
        jScrollPane2.setViewportView(newTaskTextArea);

        estimatedTimeTextArea.setText("Estimated time ");

        okNewTask.setText("Ok ");
        okNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNewTaskActionPerformed(evt);
            }
        });

        cancelNewTask.setText("Cancel ");
        cancelNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estimatedTimeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(newEstimatedTimeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(okNewTask)
                .addGap(18, 18, 18)
                .addComponent(cancelNewTask)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(newTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedTimeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEstimatedTimeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okNewTask)
                    .addComponent(cancelNewTask))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
CommonTasksList commonTasksList = new CommonTasksList();

    private void newTaskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTaskNameActionPerformed
        // Get the task name entered by the user
        String taskName = newTaskName.getText().trim();

        // Get the estimated time from the slider
        int estimatedTime = newEstimatedTimeSlider.getValue();

        // Create a new task with the data entered by the user
        CommonTasks newTask = new CommonTasks(taskName, estimatedTime);

        // Add the new task to the common tasks list
        commonTasksList.addTask(newTask);

        //Update the task list display
        // parent.updateTaskList();

    }//GEN-LAST:event_newTaskNameActionPerformed

    private void cancelNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewTaskActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel creating a new task?", "Confirm Cancel", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); //gets rid of the screen  
        }
    }//GEN-LAST:event_cancelNewTaskActionPerformed

    private void okNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNewTaskActionPerformed
        // Get the task name entered by the user
        String taskName = newTaskTextArea.getText().trim();
        // Check if the task name is empty
        if (taskName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a task name.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Check if the task name contains only letters
        for (char c : taskName.toCharArray()) {
            if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                JOptionPane.showMessageDialog(this, "Task name can only contain letters and spaces.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Add the new task to the main window's chore list
        mainWindow.AddNewChore(taskName);
        // Close the dialog
        this.dispose();

    }//GEN-LAST:event_okNewTaskActionPerformed

    /**
     * @param args the command line arguments
     * helo 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTaskChore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTaskChore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTaskChore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTaskChore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNewTask;
    private javax.swing.JTextField estimatedTimeTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSlider newEstimatedTimeSlider;
    private javax.swing.JTextField newTaskName;
    private javax.swing.JTextArea newTaskTextArea;
    private javax.swing.JButton okNewTask;
    // End of variables declaration//GEN-END:variables
}
